from __future__ import annotations

DEFAULT_SEED_SENTENCES: list[str] = [
    "The morning light spilled gently across the quiet kitchen table.",
    "She wondered whether the train would arrive before the storm did.",
    "He counted the coins twice, then slipped them into his coat pocket.",
    "A soft breeze carried the smell of fresh bread down the narrow street.",
    "They laughed about the mix-up long after the meeting had ended.",
    "The old dog stretched, yawned, and settled back into the sun.",
    "I still remember the way the river sounded at dawn.",
    "Please remember to water the plants while we are away.",
    "The children built a fort from blankets and kitchen chairs.",
    "Every evening the lighthouse blinked steadily across the bay.",
    "Could you pass me the map before we lose our way again?",
    "Her voice was calm even when the news was hard to hear.",
    "The market stalls glowed with lanterns as night crept in.",
    "We agreed to meet beneath the clock at half past seven.",
    "He practiced the same three chords until his fingers ached.",
    "The letter arrived weeks late, but its words still mattered.",
    "Snow settled on the rooftops like a slow, patient blanket.",
    "She traced the coastline with her finger and planned the trip.",
    "Nobody expected the little shop to become so beloved.",
    "The engine coughed once, then hummed to life at last.",
    "A single candle was enough to light the whole small room.",
    "They whispered so the sleeping baby would not stir.",
    "The garden grew wilder and more beautiful every summer.",
    "He read the recipe aloud while she gathered the spices.",
    "Rain tapped against the window like a familiar friend.",
    "We watched the kites climb higher until they were specks.",
    "The teacher smiled and told us to trust our own questions.",
    "A warm cup of tea can make almost any afternoon better.",
    "The path forked, and we chose the one that climbed uphill.",
    "She folded the map carefully and tucked it into her bag.",
    "The clock in the hall chimed softly through the empty house.",
    "He waved until the ferry was only a dot on the water.",
    "Their new neighbors brought over a plate of warm cookies.",
    "The library stayed open late during the week of exams.",
    "A gentle rain washed the dust from the summer leaves.",
    "We planted tomatoes along the fence in early spring.",
    "The musician tuned her violin beneath the flickering streetlamp.",
    "He mailed the postcard just before the office closed.",
    "The waves rolled in slowly, then pulled the sand away.",
    "She hummed an old tune while sweeping the front porch.",
    "The bakery sold out of pastries before the clock struck nine.",
    "They mapped the trail together and marked every water source.",
    "A curious fox paused at the edge of the frozen field.",
    "The kettle whistled just as the guests knocked on the door.",
    "He sketched the mountains from memory during the long flight.",
    "We stacked the firewood high before the cold arrived.",
    "The choir's voices rose and filled the little stone chapel.",
    "She saved the best seat by the window for her grandmother.",
    "The ferry horn echoed twice across the misty harbor.",
    "They named the puppy after the street where they first met.",
]

DEFAULT_KEYWORDS: list[str] = [
    "harbor", "lantern", "orchard", "railway", "meadow", "compass", "harvest",
    "workshop", "bicycle", "notebook", "umbrella", "cottage", "festival", "bridge",
    "telescope", "campfire", "garden", "market", "letter", "voyage", "mountain",
    "river", "bakery", "library", "harmony", "journey", "sunrise", "twilight",
    "blossom", "seashore",
]

DEFAULT_TOPICS: list[str] = [
    "everyday routines", "travel and places", "family and friends", "nature and seasons",
    "food and cooking", "work and craft", "music and art", "weather", "childhood memories",
    "small adventures", "the neighborhood", "hobbies", "learning something new", "the sea",
    "city life", "the countryside",
]
