# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import givemedata_pb2 as givemedata__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in givemedata_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GiveMeDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/GiveMeData/Init',
                request_serializer=givemedata__pb2.InitRequest.SerializeToString,
                response_deserializer=givemedata__pb2.InitResponse.FromString,
                _registered_method=True)
        self.Data = channel.stream_stream(
                '/GiveMeData/Data',
                request_serializer=givemedata__pb2.DataRequest.SerializeToString,
                response_deserializer=givemedata__pb2.DataResponse.FromString,
                _registered_method=True)
        self.Asset = channel.unary_stream(
                '/GiveMeData/Asset',
                request_serializer=givemedata__pb2.AssetRequest.SerializeToString,
                response_deserializer=givemedata__pb2.AssetResponse.FromString,
                _registered_method=True)
        self.Checkpoint = channel.stream_unary(
                '/GiveMeData/Checkpoint',
                request_serializer=givemedata__pb2.CheckpointRequest.SerializeToString,
                response_deserializer=givemedata__pb2.CheckpointResponse.FromString,
                _registered_method=True)
        self.Metrics = channel.stream_unary(
                '/GiveMeData/Metrics',
                request_serializer=givemedata__pb2.MetricsRequest.SerializeToString,
                response_deserializer=givemedata__pb2.MetricsResponse.FromString,
                _registered_method=True)
        self.End = channel.unary_unary(
                '/GiveMeData/End',
                request_serializer=givemedata__pb2.EndRequest.SerializeToString,
                response_deserializer=givemedata__pb2.EndResponse.FromString,
                _registered_method=True)


class GiveMeDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Data(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Asset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Checkpoint(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Metrics(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def End(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GiveMeDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=givemedata__pb2.InitRequest.FromString,
                    response_serializer=givemedata__pb2.InitResponse.SerializeToString,
            ),
            'Data': grpc.stream_stream_rpc_method_handler(
                    servicer.Data,
                    request_deserializer=givemedata__pb2.DataRequest.FromString,
                    response_serializer=givemedata__pb2.DataResponse.SerializeToString,
            ),
            'Asset': grpc.unary_stream_rpc_method_handler(
                    servicer.Asset,
                    request_deserializer=givemedata__pb2.AssetRequest.FromString,
                    response_serializer=givemedata__pb2.AssetResponse.SerializeToString,
            ),
            'Checkpoint': grpc.stream_unary_rpc_method_handler(
                    servicer.Checkpoint,
                    request_deserializer=givemedata__pb2.CheckpointRequest.FromString,
                    response_serializer=givemedata__pb2.CheckpointResponse.SerializeToString,
            ),
            'Metrics': grpc.stream_unary_rpc_method_handler(
                    servicer.Metrics,
                    request_deserializer=givemedata__pb2.MetricsRequest.FromString,
                    response_serializer=givemedata__pb2.MetricsResponse.SerializeToString,
            ),
            'End': grpc.unary_unary_rpc_method_handler(
                    servicer.End,
                    request_deserializer=givemedata__pb2.EndRequest.FromString,
                    response_serializer=givemedata__pb2.EndResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GiveMeData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GiveMeData', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GiveMeData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GiveMeData/Init',
            givemedata__pb2.InitRequest.SerializeToString,
            givemedata__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Data(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/GiveMeData/Data',
            givemedata__pb2.DataRequest.SerializeToString,
            givemedata__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Asset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/GiveMeData/Asset',
            givemedata__pb2.AssetRequest.SerializeToString,
            givemedata__pb2.AssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Checkpoint(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/GiveMeData/Checkpoint',
            givemedata__pb2.CheckpointRequest.SerializeToString,
            givemedata__pb2.CheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Metrics(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/GiveMeData/Metrics',
            givemedata__pb2.MetricsRequest.SerializeToString,
            givemedata__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def End(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GiveMeData/End',
            givemedata__pb2.EndRequest.SerializeToString,
            givemedata__pb2.EndResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
