"""baseline

Revision ID: fbcd07e2d59d
Revises: 
Create Date: 2026-07-09 13:17:01.603303
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbcd07e2d59d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucket_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sealed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('extra_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initialization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_initialized', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hf_token', sa.Text(), nullable=False),
    sa.Column('openrouter_token', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('graph_request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('node_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'node_id', name='uq_node_logs_run_node')
    )
    op.create_index(op.f('ix_node_logs_node_id'), 'node_logs', ['node_id'], unique=False)
    op.create_index(op.f('ix_node_logs_run_id'), 'node_logs', ['run_id'], unique=False)
    op.create_table('runners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=False),
    sa.Column('port', sa.BigInteger(), nullable=False),
    sa.Column('gpu_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bucket', sa.Text(), nullable=False),
    sa.Column('folder', sa.Text(), nullable=False),
    sa.Column('endpoint_url', sa.Text(), nullable=False),
    sa.Column('region_name', sa.String(length=64), nullable=False),
    sa.Column('access_key_id', sa.Text(), nullable=False),
    sa.Column('secret_access_key', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('waveform_packs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sealed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('bucket_file_id', sa.UUID(), nullable=False),
    sa.Column('byte_offset', sa.BigInteger(), nullable=False),
    sa.Column('byte_length', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('virtual', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bucket_file_id'], ['bucket_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistics_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_entries_dataset_id'), 'statistics_entries', ['dataset_id'], unique=False)
    op.create_table('audio_waveforms',
    sa.Column('audio_file_id', sa.UUID(), nullable=False),
    sa.Column('pack_id', sa.UUID(), nullable=False),
    sa.Column('byte_offset', sa.BigInteger(), nullable=False),
    sa.Column('byte_length', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('points_per_second', sa.Integer(), nullable=False),
    sa.Column('point_count', sa.Integer(), nullable=False),
    sa.Column('format_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ),
    sa.ForeignKeyConstraint(['pack_id'], ['waveform_packs.id'], ),
    sa.PrimaryKeyConstraint('audio_file_id')
    )
    op.create_table('dataset_audio_files',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('audio_file_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('dataset_id', 'audio_file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_audio_files')
    op.drop_table('audio_waveforms')
    op.drop_index(op.f('ix_statistics_entries_dataset_id'), table_name='statistics_entries')
    op.drop_table('statistics_entries')
    op.drop_table('audio_files')
    op.drop_table('workflows')
    op.drop_table('waveform_packs')
    op.drop_table('voices')
    op.drop_table('storage_settings')
    op.drop_table('runners')
    op.drop_index(op.f('ix_node_logs_run_id'), table_name='node_logs')
    op.drop_index(op.f('ix_node_logs_node_id'), table_name='node_logs')
    op.drop_table('node_logs')
    op.drop_table('jobs')
    op.drop_table('integration_settings')
    op.drop_table('initialization')
    op.drop_table('extra_files')
    op.drop_table('datasets')
    op.drop_table('configs')
    op.drop_table('checkpoints')
    op.drop_table('bucket_files')
    # ### end Alembic commands ###
