import re
from runner.nodes.text_processing.polish_cardinals import article_number_is_quantity, has_incompatible_cardinal_noun
from runner.nodes.text_processing.polish_compounds import (
    age_adjective_words as _age_adjective_words,
    currency_noun_phrase as _currency_noun_phrase, demonstrative_cardinal_words, dotted_group_words, expand_coordinated_measurements, expand_dimensions, has_ambiguous_dotted_group,
    expand_age_pair_labels, expand_grouped_scales,
)
from runner.nodes.text_processing.polish_grammar import ORDINAL_LEMMAS, expand_morphological_numbers, expand_number_roles, feminine_cardinal, has_unsafe_number_syntax, nominative_ordinal_for_noun
from runner.nodes.text_processing.polish_inflections import (
    cardinal as _cardinal,
    feminine_accusative_ordinal as _feminine_accusative_ordinal,
    feminine_genitive_ordinal as _feminine_ordinal,
    feminine_nominative_ordinal as _feminine_nominative_ordinal,
    genitive_cardinal as _genitive_cardinal,
    genitive_ordinal as _genitive_ordinal,
    locative_cardinal as _locative_cardinal, locative_ordinal as _locative_ordinal,
    ordinal as _ordinal,
)
from runner.nodes.text_processing.polish_orthography import BIBLE_REFERENCE_RE, SPORTS_RECORD_RE, restore_numeric_sentence_capitals
from runner.nodes.text_processing.polish_percentages import (
    decimal_words as _decimal_words,
    expand_contextual_percentages, governed_percent_words as _governed_percent_words,
    has_ambiguous_negated_percent, negated_percent_words as _negated_percent_words, number_words as _number_words,
)
from runner.nodes.text_processing.polish_ranges import (
    age_range_words as _age_range_words,
    has_invalid_mixed_range,
    po_alternative_words as _po_alternative_words,
    range_percent_words as _range_percent_words,
    range_words as _range_words,
)
from runner.nodes.text_processing.polish_scales import expand_embedded_cardinal_scales, expand_locative_scale_contexts
from runner.nodes.text_processing.polish_temporal import (
    clock_words as _clock_words,
    date_pair_words as _date_pair_words,
    date_range_words as _date_range_words,
    date_words as _date_words,
    decade_words as _decade_words,
    expand_completion_minutes,
    expand_context_comma_clocks as _expand_context_comma_clocks,
    governed_clock_words as _governed_clock_words,
    CONTEXTUAL_DATE_RE, has_invalid_date,
    lat_decade_pair_words as _lat_decade_pair_words, lat_decade_words as _lat_decade_words,
    lata_decade_list_words as _lata_decade_list_words,
    lata_decade_words as _lata_decade_words,
    minute_alternative_words as _minute_alternative_words,
    o_clock_words as _o_clock_words,
    short_year_after_words, time_range_words as _time_range_words,
    year_after_in_words, year_list_words as _year_list_words, year_pair_words as _year_pair_words, year_words as _year_words,
)
MONTHS = "stycznia|lutego|marca|kwietnia|maja|czerwca|lipca|sierpnia|września|października|listopada|grudnia"
DATE_RE = re.compile(rf"(?<!po )\b(?P<day>[1-9]|[12][0-9]|3[01]) (?P<month>{MONTHS})(?: (?P<year>\d{{4}}|\d{{3}}(?= roku))(?P<roku> roku)?)?\b", re.IGNORECASE)
SUBJECT_DATE_RE = re.compile(rf"(?:(?P<boundary>^|[.!?]\s+)\b(?P<day>[1-9]|[12][0-9]|3[01]) (?P<month>{MONTHS})(?= (?:nie )?(?:jest|był|będzie)\b)|(?P<arrival>\b(?:nadchodzi|nadejdzie|nadszedł) )(?P<arrival_day>[1-9]|[12][0-9]|3[01]) (?P<arrival_month>{MONTHS}))", re.IGNORECASE)
MASCULINE_SUBJECT_DATE_RE = re.compile(rf"\b(?P<prefix>roku )(?P<day>[1-9]|[12][0-9]|3[01]) (?P<month>{MONTHS})(?= (?:nie )?był\b)", re.IGNORECASE)
DEMONSTRATIVE_DATE_RE = re.compile(rf"\bpo (?P<context>tym|dniu|moim|twoim|jego|jej|naszym|waszym|ich) (?P<day>[1-9]|[12][0-9]|3[01]) (?P<month>{MONTHS})\b", re.IGNORECASE)
ACCUSATIVE_DATE_RE = re.compile(rf"\b(?P<prefix>o|na|ten|przed|jest(?: już)?|to będzie|(?:to był|był to)|(?:czym|tym) innym (?:jest|będzie|był)|to (?:jest|był)(?: (?:chyba|pewnie|prawdopodobnie))?|mam|mamy|(?:\w+ )?dniem był) (?P<day>[1-9]|[12][0-9]|3[01]) (?P<month>{MONTHS})(?: (?P<year>\d{4})(?P<roku> roku)?)?(?! \d{4}\b)\b", re.IGNORECASE)
PASSIVE_DATE_RE = re.compile(rf"\b(?P<prefix>\w+(?:ny|ty|na|ta|ne|te) jest) (?P<day>[1-9]|[12][0-9]|3[01]) (?P<month>{MONTHS})\b", re.IGNORECASE)
DATE_PAIR_RE = re.compile(rf"\b(?P<first>[1-9]|[12][0-9]|3[01]) (?P<link>i|lub|albo|na) (?P<second>[1-9]|[12][0-9]|3[01]) (?P<month>{MONTHS})\b", re.IGNORECASE)
DATE_RANGE_RE = re.compile(rf"\bod (?P<first>[1-9]|[12][0-9]|3[01]) do (?P<second>[1-9]|[12][0-9]|3[01]) (?P<month>{MONTHS})\b", re.IGNORECASE)
YEAR_RE = re.compile(r"\b(?P<year>\d{3,4}) roku\b")
YEAR_IN_RE = re.compile(r"\b(?P<prefix>w|we|o) (?P<modifier>(?:\w+ ){0,2}\w+(?:ym|im) )?(?P<year>\d{3,4}) roku\b", re.IGNORECASE)
YEAR_AFTER_IN_RE = re.compile(r"\b(?P<prefix>w(?: ciągu)?) roku (?P<year>[12][0-9]{3})\b", re.IGNORECASE)
YEAR_AFTER_RE = re.compile(r"\b(?P<governor>(?:o|po|w) )?(?P<prefix>roku) (?P<year>\d{3,4})\b(?!\s+(?:tysiąc|tysiące|tysięcy|milion|miliony|milionów|miliard|miliardy|miliardów)\b)", re.IGNORECASE)
YEAR_AFTER_PO_RE = re.compile(r"\b(?P<prefix>po(?: około)?) (?P<year>\d{3,4}) roku\b", re.IGNORECASE)
YEAR_NOMINATIVE_RE = re.compile(r"\b(?P<year>[12][0-9]{3}) rok\b")
SHORT_YEAR_RE = re.compile(r"\b(?P<prefix>w) (?P<year>\d{2}) roku\b", re.IGNORECASE)
SHORT_YEAR_NOMINATIVE_RE = re.compile(r"\b(?P<year>\d{2}) rok\b", re.IGNORECASE)
SHORT_YEAR_AFTER_RE = re.compile(r"\b(?P<prefix>rok) (?P<year>\d{2})\b", re.IGNORECASE)
YEAR_TARGET_RE = re.compile(r"\b(?P<prefix>na) (?P<year>[12]\d{3})(?=\s+(?:przewidywano|planowano))", re.IGNORECASE)
YEAR_BEFORE_RE = re.compile(r"\b(?P<prefix>przed) (?P<year>[12]\d{3}) rokiem\b", re.IGNORECASE)
YEAR_AFTER_ROK_RE = re.compile(r"\b(?P<prefix>rok) (?P<year>[12]\d{3})\b", re.IGNORECASE)
YEAR_LIST_RE = re.compile(r"\bw (?P<first>[12]\d{3}), (?P<second>[12]\d{3}) roku\b", re.IGNORECASE)
YEAR_PAIR_RE = re.compile(r"\b(?P<prefix>w )?(?P<first>[12]\d{3}) (?P<link>i|oraz|lub|albo) (?P<second>[12]\d{3}) roku\b", re.IGNORECASE)
YEAR_IN_PAIR_RE = re.compile(r"\b(?P<prefix>w roku) (?P<first>[12]\d{3}) (?P<link>i|oraz) (?P<second>[12]\d{3})\b", re.IGNORECASE)
THIS_YEAR_RE = re.compile(r"\bw tym roku (?P<year>[12]\d{3})\b", re.IGNORECASE)
END_YEAR_RE = re.compile(r"\bdo końca (?P<year>[12]\d{3})\b", re.IGNORECASE)
LOCATIVE_MONTH_YEAR_RE = re.compile(r"\b(?P<prefix>w|we) (?P<month>styczniu|lutym|marcu|kwietniu|maju|czerwcu|lipcu|sierpniu|wrześniu|październiku|listopadzie|grudniu) (?P<year>[12]\d{3})\b", re.IGNORECASE)
MONTH_YEAR_RE = re.compile(r"\b(?P<month>styczeń|luty|marzec|kwiecień|maj|czerwiec|lipiec|sierpień|wrzesień|październik|listopad|grudzień) (?P<year>[12]\d{3})\b", re.IGNORECASE)
DECADE_RE = re.compile(r"\b(?P<prefix>w )?(?P<stem>latach) (?P<decade>[2-9]0)(?P<dot>[.'’]?)", re.IGNORECASE)
LAT_DECADE_RE = re.compile(r"\b(?P<prefix>(?:(?:z|do|od|początku|koniec) )?lat) (?P<decade>[2-9]0)(?P<dot>[.'’]?)", re.IGNORECASE)
LATA_DECADE_RE = re.compile(r"\b(?P<prefix>Lata) (?P<decade>[2-9]0)(?P<dot>[.'’]?)", re.IGNORECASE)
LAT_DECADE_PAIR_RE = re.compile(r"\blat (?P<first>[2-9]0)[.]? (?P<link>i|oraz|lub|albo) (?P<second>[2-9]0)(?P<dot>[.]?)", re.IGNORECASE)
LATA_DECADE_LIST_RE = re.compile(r"\b(?P<prefix>Lata) (?P<first>[2-9]0)[.], (?P<second>[2-9]0)[.]", re.IGNORECASE)
AGE_AFTER_LAT_RE = re.compile(r"\b(?P<prefix>mam|mamy|masz|ma|miał|miała|mieli|mając) lat (?P<value>\d+)\b", re.IGNORECASE)
RANGE_RE = re.compile(r"\b(?P<start>\d+)\s*[-–]\s*(?P<end>\d+)(?=\s+(?:lat|minut|sekund|godzin|metr|kilometr|gram|stopni)\b)", re.IGNORECASE)
GENERIC_RANGE_RE = re.compile(r"(?<![\w])(?P<start>\d+)\s*[-–]\s*(?P<end>\d+)(?![\w])")
PO_ALTERNATIVE_RE = re.compile(r"\bpo (?P<first>\d+) (?:czy|lub|albo) (?P<second>\d+)(?=\s+[A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż]+)", re.IGNORECASE)
GROUPED_NUMBER_RE = re.compile(r"\b\d{1,3}(?: \d{3})+\b"); GOVERNED_GROUPED_NUMBER_RE = re.compile(r"\b(?P<prefix>od|do|do kwoty|około|blisko|poniżej|powyżej|sprzed|w wysokości|o powierzchni|na wysokości|w odległości|wartości|skończ\w*(?: się)?(?: tylko)? na) (?P<value>\d{1,3}(?: \d{3})+)\b", re.IGNORECASE)
DOTTED_GROUPED_NUMBER_RE = re.compile(r"\b\d{1,3}(?:[.]\d{3})+\b")
AGE_RANGE_RE = re.compile(r"\bwieku (?P<start>\d+)\s*[-–]\s*(?P<end>\d+)(?=\s+lat(?:ka)?\b)", re.IGNORECASE)
PERCENT_RANGE_RE = re.compile(r"\b(?P<prefix>około )?(?P<start>\d+)\s*[-–]\s*(?P<end>\d+)\s*%", re.IGNORECASE)
PERCENT_RE = re.compile(r"\b(?P<value>\d+(?:[,.]\d+)?)\s*%")
GOVERNED_PERCENT_RE = re.compile(r"\b(?P<prefix>dotycz\w*|(?:wzr(?:(?:o|ó)[sś]|ast)\w*|spad\w*|zwiększ\w*|zmniejsz\w*) (?:się )?o|na poziomie|na około|do poziomu|w okolicach|blisko|dla|mimo|od|do|rzędu|około tam|(?<!\bo )około|poniżej|powyżej|przy|wobec|wśród|w|z|o) (?P<modifier>(?:(?:bodajże|maksymalnie|mniej więcej|niemal|około|ponad|prawie|przynajmniej|tylko|zaledwie) )?)(?P<value>\d+(?:[,.]\d+)?)\s*%", re.IGNORECASE)
CLOCK_RE = re.compile(r"\b(?P<prefix>około |jest godzina |jest )(?P<hour>[01]?\d|2[0-3])[.:](?P<minute>[0-5]\d)\b", re.IGNORECASE)
COORDINATED_CLOCK_RE = re.compile(r"\b(?P<prefix>w okolicach|na|od|do|po) (?P<hour>[01]?\d|2[0-3])[.:](?P<minute>[0-5]\d)\b", re.IGNORECASE)
HOUR_CLOCK_RE = re.compile(r"\b(?P<prefix>o godzinie|do godziny|przed godziną) (?P<hour>[01]?\d|2[0-3]|24)(?:[.:,](?P<minute>[0-5]\d))?\b", re.IGNORECASE)
MODIFIED_GOVERNED_RE = re.compile(r"\b(?P<prefix>po przejechaniu|na przestrzeni) (?P<modifier>(?:kolejnych|nawet) )?(?P<value>\d+)\b", re.IGNORECASE)
PRZEZ_OKOLO_RE = re.compile(r"\b(?P<prefix>przez|na|za) (?P<modifier>około|ponad) (?P<value>\d+)\b(?!\s*%)", re.IGNORECASE)
SPRZED_PONAD_RE = re.compile(r"\b(?P<prefix>sprzed(?: ponad)?|przed(?= \d+ laty\b)) (?P<value>\d+)(?! roku\b)(?: (?P<unit>laty))?\b", re.IGNORECASE)
DEMONSTRATIVE_GOVERNED_RE = re.compile(r"\b(?P<prefix>od|do|około|z|w|o|po) (?P<modifier>tych|pełnych) (?P<value>\d+)\b", re.IGNORECASE)
DEMONSTRATIVE_RE = re.compile(r"\b(?P<modifier>tych) (?P<value>\d+)\b", re.IGNORECASE)
FEMININE_DEMONSTRATIVE_RE = re.compile(r"\b(?P<prefix>w|do) tej (?P<value>\d+)\b(?!\s*%)", re.IGNORECASE)
AGE_YEAR_RE = re.compile(r"\b(?P<prefix>od) (?P<value>\d+) roku życia\b", re.IGNORECASE)
AGE_YEAR_AFTER_RE = re.compile(r"\b(?P<prefix>po|w około) (?P<value>\d+) roku życia\b", re.IGNORECASE)
AGE_YEAR_ABOVE_RE = re.compile(r"\b(?P<prefix>powyżej) (?P<value>\d+) roku życia\b", re.IGNORECASE)
DIMENSION_RE = re.compile(r"\b\d+(?:\s*[x×]\s*\d+)+\b", re.IGNORECASE)
AGE_ADJECTIVE_RE = re.compile(r"\b(?P<prefix>u )?(?P<value>\d{1,3})(?:-| (?=lat(?:ka|ką|ek)|litrowy|kilogramowych|centymetrowy|bitow\w*|stronicow\w*|krotnoś\w*\b))(?P<suffix>letni|letnia|letnią|letnie|letnich|letnim|letniego|latkowie|latka|latką|latek|litrowy|kilogramowych|centymetrowy|minutowy|minutowa|minutowe|miesięczny|miesięczna|miesięczne|lecie|tysięczny|tysięcznego|calowy|calowa|gigowy|gigowa|bitowy|bitowa|bitową|bitowe|bitowych|bitowym|bitowego|stronicowy|stronicowa|stronicową|stronicowe|stronicowej|stronicowego|stronicowych|stronicowym|stronicowymi|krotność|krotności)\b", re.IGNORECASE)
EXPLICIT_ORDINAL_RE = re.compile(r"\b(?P<value>\d+)[.] (?P<noun>odcinek|urodziny|miejsce|rozdział)\b", re.IGNORECASE)
FEMININE_GENITIVE_ORDINAL_RE = re.compile(r"\b(?P<value>\d+)[.] (?P<noun>rocznicy|edycji|wersji|serii|strony|frakcji)\b", re.IGNORECASE)
LOCATIVE_POSITION_RE = re.compile(r"\b(?:(?P<prefix>na miejscu) (?P<value>\d+)|(?P<verb>(?:znajd\w*|(?:u)?plas\w*) się na) (?P<static_value>\d+)[.]? miejsce)\b", re.IGNORECASE)
NOMINATIVE_ORDINAL_RE = re.compile(r"\b(?P<value>\d+) (?P<noun>równoleżnik|korpus)\b", re.IGNORECASE)
KILOMETER_ORDINAL_RE = re.compile(r"\bkilometra (?P<value>\d+)\b", re.IGNORECASE)
DAY_NUMBER_RE = re.compile(r"\b(?P<prefix>od|do) dnia (?P<value>\d+)\b", re.IGNORECASE)
DAY_ORDINAL_RE = re.compile(r"\b(?P<prefix>do|powyżej|wprowadzon\w*) (?P<value>\d+) dnia\b", re.IGNORECASE)
BCE_YEAR_RE = re.compile(r"\b(?P<prefix>W|w) (?P<year>\d{3}) r[.]", re.IGNORECASE)
ARTICLE_ORDINAL_RE = re.compile(r"\b(?P<noun>artykuł|artykule|artykułu|ustęp|ustępie|ustępu|ust[.]) (?P<value>\d+)\b", re.IGNORECASE)
O_CLOCK_RE = re.compile(r"\b(?P<prefix>o) (?P<hour>[01]?\d|2[0-3])[.:,](?P<minute>[0-5]\d)\b", re.IGNORECASE)
HOUR_ACCUSATIVE_RE = re.compile(r"\b(?P<prefix>o |na )?(?P<noun>godzinę) (?P<hour>[01]?\d|2[0-3])\b(?!\s+(?:minut|sekund)\b)", re.IGNORECASE)
HOUR_GENITIVE_RE = re.compile(r"\b(?P<noun>godziny) (?P<hour>[01]?\d|2[0-3])\b(?!\s+minut)", re.IGNORECASE)
HOUR_BEFORE_RE = re.compile(r"\bprzed godziną (?P<hour>[01]?\d|2[0-3])\b(?![.:,]\d)", re.IGNORECASE)
CONTEXT_COMMA_CLOCK_RE = re.compile(r"\b(?P<prefix>w minucie|godzin(?:a|ę)(?: [A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż]+){0,3}?|[A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż]+ to|(?:zacz|rozpocz|skończ|kończ)\w*(?: się)?|godzinę[^.!?]{0,30}?(?:jest tam|pokazuje)) (?P<hour>[01]?\d|2[0-3])[,.:](?P<minute>[0-5]\d)\b|^(?P<bare_hour>[01]?\d|2[0-3])[.:](?P<bare_minute>[0-5]\d)(?=,\s+[^.!?]{0,40}\bod godziny\b)|(?<![\d.])(?P<clause_hour>[01]?\d|2[0-3])[.](?P<clause_minute>[0-5]\d)(?=,\s*(?:jak|kiedy|gdy)\b)", re.IGNORECASE)
O_RANO_RE = re.compile(r"\bo (?P<hour>[1-9]|1\d|2[0-3]) rano\b", re.IGNORECASE)
APPROXIMATE_RANO_RE = re.compile(r"\bokoło (?P<hour>[1-9]|1\d|2[0-3]) rano\b", re.IGNORECASE)
TIME_RANGE_RE = re.compile(r"\bo tej (?P<first>[1-9]|1\d|2[0-3]) do (?P<second>[1-9]|1\d|2[0-3])\b", re.IGNORECASE)
MINUTE_ALTERNATIVE_RE = re.compile(r"\btę (?P<first>\d+) (?:czy|lub|albo) (?P<second>\d+) minutę\b", re.IGNORECASE)
WORK_UNTIL_RE = re.compile(r"\bPracuję do (?P<hour>[1-9]|1\d|2[0-3])\b", re.IGNORECASE)
DEMONSTRATIVE_PERCENT_RE = re.compile(r"\b(?P<prefix>na|w|o|po) tych (?P<value>\d+)\s*%", re.IGNORECASE)
THOSE_PERCENT_RE = re.compile(r"\btych (?P<value>\d+)\s*%", re.IGNORECASE)
PERCENT_CONTEXT_RE = re.compile(r"\bw granicach (?P<value>\d+(?:[,.]\d+)?)\s*%", re.IGNORECASE)
NEGATED_QUANTITY_RE = re.compile(r"\bnie przekracza (?P<value>\d+)\b", re.IGNORECASE)
NEGATED_PERCENT_RE = re.compile(r"\b(?P<prefix>nie (?P<governor>\w+)(?: jeszcze)? )(?P<value>\d+)\s*%", re.IGNORECASE)
CURRENCY_RE = re.compile(r"\b(?P<value>\d+)\s*[$€£]")
DECIMAL_RE = re.compile(r"\b(?P<whole>\d+)[,.](?P<fraction>\d+)\b")
DIGIT_RE = re.compile(r"[0-9]")
UNSAFE_NUMERIC_RE = re.compile(r"(?<![\d:.])0\d+\b|\b\d+(?:[-–]\d+){2,}\b|\b\d{4}[-–]\d{2,4}\b|\b[3-9]\d{3} roku\b|\b\d{6,}\b|\b\d{5,} roku\b")
UNSAFE_CONTEXT_RE = re.compile(r"\b(?:numer|nr[.]?) \d{1,3}(?: \d{2,3})+\b|\bstan\w* \d+ kompanii\b|,\s*\w+(?:ej|ym|im) \d+ (?:tysięcy|milionów|miliardów)\b|\b\w+(?:ej|ym|im|y) wcześniej \d+ (?:tysięcy|milionów|miliardów)\b|\b\d+ lat \d{2}[.]|\bpod \d+ lat temu\b|\bkąt \d|\b\d+\s+(?-i:[A-ZĄĆĘŁŃÓŚŹŻ]{2,})\b|\b(?:wraz z|między) \d|\bPolsk\w* \d{4}\b|\bRTX \d|\b[FUN] \d{2,}\b|\b[A-Z][.]\d|\b(?-i:[A-ZĄĆĘŁŃÓŚŹŻ]{2,}) \d+\b|\b(?-i:[A-ZĄĆĘŁŃÓŚŹŻ]\w+ [A-ZĄĆĘŁŃÓŚŹŻ]\w+) \d+\b|\b(?-i:[A-ZĄĆĘŁŃÓŚŹŻ][a-ząćęłńóśźż]+) \d+ z \d+\b|\b\d+x\d+(?:[.]\w|\s+(?:minut|godzin|sekund)\w*\b)|\bstron(?:ie|ach|y) \d{1,3}[.]\d{1,3}\b|\b[A-Za-z]+-\d+[,.]\d+", re.IGNORECASE)
UNSAFE_HYPHEN_WORD_RE = re.compile(r"\b\d+-[A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż]+\b|\b[A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż]+-\d+\b")
UNSAFE_DECIMAL_NOUN_RE = re.compile(r"\b\d+[,.]\d+\s+[A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż]+\b")
UNSAFE_LABELED_DECIMAL_RE = re.compile(r"^\d{1,2}[.]\d{1,2},|\b\d+[.]0+\b|\b\d+[.]\d+[.]|\b\d+[.]\d{1,2}\b|\badres\w* mailow\w*(?: \w+){0,2} \d+[,.]\d+\b|\b(?:model|peron|utw(?:ó|o)r)\w*(?: z)? \d+[.,]\d+\b|\b(?:urządzenia|wersji|serii|typu|numeru) \d+[,.]\d{3,}\b|\bo miejsc\w*[^.!?]{0,80}\b\d{1,3},\d{1,3}\b", re.IGNORECASE)
AGO_YEARS_RE = re.compile(r"\b(?P<prefix>(?:około|blisko) )?(?P<value>\d+) lat temu\b", re.IGNORECASE)
AFTER_DURATION_RE = re.compile(r"\b(?P<value>\d+) lat (?P<link>po)\b", re.IGNORECASE)
UNSAFE_GRAMMAR_RE = re.compile(r"^\d+[.]\d+[.]|\b\d+(?:,\d+){2,}\b|\bczas w okolicach \d+[:.]\d+|\b(?:z ponad|z tymi) \d|\bz \d+[,;] \d|\bz \d{2,3} \d{3}\b|\bnie \w+ \d+ (?P<negated_list_unit>[A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż]+), \d+ (?P=negated_list_unit)\b|\b(?:od|z|na) \d+(?: (?:tysiąc|tysiące|tysięcy|milion|miliony|milionów))? lat temu\b|\bprzed \d+ lat\b|\b(?:na \d+ roku|około na \d)|\bpo \d+[-–]\d+|\b(?:lata \d{4}|lat \d{3,4} roku)|\bw latach \d+ rok\b|\bw \d+ chyba\b|\btysiąc \d+ rok\b|\bnie(?: \w+){1,3} \d+[,.]\d+%|\bte \d+[,.]\d+%|\b(?:artyk\w+|klauzul\w*|punk\w*|sekcj\w*|wersj\w*|rozdzia\w*|przepis\w*|n(?:r|umer))[.!:]? \d+[,.]\d+|\bwedług \w+ \d+[.]\d+(?=[,.;])|\bprzez \d+ roku\b|\bna początek lata \d|\b(?:jest|był\w*|będ\w+) \d+% \w+(?:em|ą)\b|(?<!w )\b\d+% (?:się )?\w+ć\b|\b\w+(?:ej|ym|im) \d+%|\bw \w+ś \d+%|\bza (?:tych|te) \d+%|\b(?:na|o|z) \d+%|\bo (?:około|ponad) \d+%|\btych(?: \w+){1,2} \d+%|\b\w+(?:ciem|niem),? (?:zdaje się,? )?\d+%|\bjest \d+ stopni do \w+", re.IGNORECASE)
UNSAFE_NOUN_RANGE_RE = re.compile(r"\b\d+[-–]\d+\s+[A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż]+\b")
UNSAFE_SPACED_ALTERNATIVE_RE = re.compile(r"\bza \d{2,3} \d{2,3} (?:czy|lub|albo)\b|\b[0-7],[0-7](?:,\s+[0-7],[0-7])+\b", re.IGNORECASE)
UNSAFE_SPACED_IDENTIFIER_RE = re.compile(r"\b[A-ZĄĆĘŁŃÓŚŹŻ][.] \d+\b")
UNSAFE_ALTERNATIVE_NOUN_RE = re.compile(r"\b\d+ (?:czy|lub|albo) \d+ [A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż]+\b", re.IGNORECASE)
UNSAFE_NOMINATIVE_DATE_RE = re.compile(rf"\b\d{{1,2}} (?:styczeń|luty|marzec|kwiecień|maj|czerwiec|lipiec|sierpień|wrzesień|październik|listopad|grudzień)\b|\b\d{{1,2}} (?:{MONTHS}) \d{{3,4}} rok\b", re.IGNORECASE)
UNSAFE_DUPLICATE_NUMBER_RE = re.compile(rf"\bw \d{{1,4}} roku,\s+\d{{3,4}} roku\b|\b(?P<value>\d+) (?P=value)\b|\b(?P<day>\d{{1,2}}) (?P<month>{MONTHS}) (?P=day) (?P=month)\b|\b\d{{4,}} \d{{3,}}\b", re.IGNORECASE)
UNSAFE_CONSECUTIVE_PERCENT_RE = re.compile(r"\b\d+(?:[,.]\d+)?%\s+\d+(?:[,.]\d+)?%|\b\d+(?:[,.]\d+)?%\s+\d+[,.]\d+\b(?!\s*%)|\b\d+(?:[,.]\d+)?%\s+(?!(?:i|oraz|lub|albo|vs|versus|wersus|wers)\b)\w+\s+\d+(?:[,.]\d+)?%", re.IGNORECASE)
UNSAFE_MALFORMED_CONTEXT_RE = re.compile(r"(?<!w )(?<!o )(?<!z )(?<!po )(?<!od )(?<!do )\b\d{1,2} roku\b(?! życia)|\bw \d+ latach\b|\bw wieku \d+%|\bo wieku \d+ lat\b|\bbył(?:a)? (?:może |około )?\d+ lat(?=[,.;!?]|$)|\bpo swojej \d+\b|\bna stopniu \d+ dni\b|\b\d+ (?:tych|tymi|miesiąca)\b|\bnumer \d+ i \d+ \d+ (?:stycznia|lutego|marca|kwietnia|maja|czerwca|lipca|sierpnia|września|października|listopada|grudnia)\b|\bpo \d+ gram \d+\b|\bod numer \d+ do numer \d+\b|\bwydarzyło się w \d{2}\b|\brokiem(?: \w+){0,2} \d{3,4} roku\b|\b\d+ lat w ciąży temu\b|\bw okolicy \d+, \d+\b|\bpod koniec \d{2} w\b|\bjosną \d{4}\b|\bmi są \d+ zł\b|\bz tysią \d+ do \d+\b|\btysiąc (?:\w+ )?\d+ roku\b|\bna rok \d{4} zdanie\b|\b\d+ tysiące ponad\b|\bbite przez \d+\b|\b\d+ metra\b|^1 nawet\b|\bdo \d+[,.]\d+%|\bduży \d+ punkty\b|\bwyborach \d{4} i\b|\bod około \d{4} mu\b|\b\d+ sekundowego\b|\b\d+ tony\b|\bprawie ponad \d+\b|\bponiżej \d+ czy \w+ \d+ lat\b|\bsprzed \d+ de facto roku\b|^\d+ Nie\b|\bsą \d+ edycja\b|\bmodemy \d+ kg\b|\bostatnim \d+ latach\b|\bwyjazd \d+ o \d|\b\d+ miliardów trzeciego\b|\bprzed \d+ zł\b|\bABC,? mają \d|\bC \d+ \d+\b|\bbrodę z \d+ lat\b|\b\d+ miliarda złotych\b|\bw pierwszej \d+\b|\b\d+[-–]\d+%|^\d+ ani\b|\bz \d+ godziny\b|\blatach \d{4} sowiecki\b|\bMinuta \d+ \d+\b|\b\d+ godzinne\b|\bw \d{4} rok\b|\b\d+ sekundowych\b|\bw swoim \w+ \d{4} roku\b|\bpierwszych \d+ pan\b|\bZa to \d+ były\b|\bprawie \d+ tysiącami\b|\[\d+\]|^(?-i:\d+ [A-ZĄĆĘŁŃÓŚŹŻ])|\bMiałem \d+ własny\b|\bpomiędzy \d+ tysięcy a \d+ tysięcy\b|\bw jeden \d{4} rok\b|\bOd \d+ i \d+\b|\bpóźniej \d{2} to\b|\bmaksymalnie \d{4} pod wiatr\b|\bz \d+[,.]\d+, prawie \d+ miesiące\b|\bpo tych \d+ lat\b|\b\d{3,4} \w+(?:szy|gi|ci|ty) rok\b|\bz tym \d|\bod koniec \d{4} roku\b|\broku \d{3,4} rok(?:u)?\b|\b\d{1,2} rok \d{4} rok\b|\b(?P<duplicate_year>\d{4}) rok, (?P=duplicate_year) rok\b|\b(?:on|ona|ono) jest \d+ lat\b|\bpo mniej \d+\b|\b\d+-letnim (?:w )?(?:swoim )?wieku\b|\bna te \d+ lat temu\b|\bw dokładnie \d{1,3}(?: \d{3})+ (?!minut|sekund|godzin|dni|tygodni|miesięcy|lat)\w+\b", re.IGNORECASE)
UNSAFE_INVERTED_CONTEXT_RE = re.compile(r"\blat \d+ i parę\b|\bw latach \d{2}[.]? czy \d{3,4} roku\b|\bbył(?:a|o)?,\s*\d+ lat\b|\bniedawno było \d+ lat(?=[,.;!?]|$)|\bwyrażon\w* w \d+ \w+ów\b", re.IGNORECASE)
UNSAFE_SOURCE_GRAMMAR_RE = re.compile(r"\bw \d{1,2} roku,\s+\d{3,4} roku\b|\bod[,;]? (?:\w+ )?od \d|\bz wśród\b|\bzśród\b|\bpo koniec\b|\bo godziny \d+\b|\bpo \w+ych lat \d+[.]|\b(?:jest|był\w*|będ\w+) po \d+ lat\b|\bz \d+-lecie\b|\b(?:na|w|z|do|od) po (?:latach|roku) \d+|\b(?:jest|był\w*|będ\w+) (?:też )?\d{3,4} roku\b|\b(?:około|ponad|prawie|niemal|blisko)[,;]? (?:no )?(?:około|ponad|prawie|niemal|blisko) \d|\b(?:od|do|około|ponad|prawie|blisko) \d+[,.]\d+\s*$|\btych \d{4}(?:\s+(?:powiedzmy|chyba))?(?=[,.;!?]|$)|\bponiż \d|\bminimum(?: \w+){1,2} załóżmy \d|\b(?:minął|upłynął) \d+ lat\b|\b\d{3,} roku życia\b|\bprzed \d{3,4} roku\b|\bpracuj(?:ę|esz|e|emy|ecie|ą) na (?:(?:jakby|już) ){0,2}\d+ lat\b|\bskładaj\w* się (?:tylko )?\d|\bbęd\w*(?: \w+){0,2} to \d+ (?-i:[A-ZĄĆĘŁŃÓŚŹŻ]\w*(?:ji|cji))\b|\bw (?:styczeń|luty|marzec|kwiecień|maj|czerwiec|lipiec|sierpień|wrzesień|październik|listopad|grudzień) \d{4} roku\b|\bz \d{1,2} (?:stycznia|lutego|marca|kwietnia|maja|czerwca|lipca|sierpnia|września|października|listopada|grudnia) i (?:stycznia|lutego|marca|kwietnia|maja|czerwca|lipca|sierpnia|września|października|listopada|grudnia) \d{4} roku\b|\bo \d+ razy\b|\b\w+ razy za \d+(?:[,.]\d+)?% więcej\b|\bod takie \d+ (?:dni|tygodni|miesięcy|lat)\b|\bna [bp]aczności \d+(?: (?:tysiąc|tysiące|tysięcy|milion|miliony|milionów))? \w+\b|\b(?:dochodzi\w* \d+ stopni|\d+ stopni (?:nie )?dochodzi\w*)\b|\b(?:około|prawie|zaledwie) na (?:około|ponad|prawie|zaledwie) \d+(?:[,.]\d+)?%", re.IGNORECASE)
UNSAFE_WORD_ORDER_RE = re.compile(r"\b\d+ ponad tysi(?:ąc|ące|ęcy)\b|\b\d+ (?:tysięcy|milionów|miliardów) (?:około|prawie|blisko)\b|\b\d{1,3}(?: \d{3})+ (?:około|prawie|ponad|blisko)\b|\b\d+(?:[,.]\d+)?% (?:około|prawie|ponad|blisko)\b|\bod (?:w )?sumie ponad \d+\b|\b\d+ lat co\b|\broku lat \d+\b|^\d{4}\s(?!roku\b)|^\d{1,3} \d{3} (?=(?-i:[A-ZĄĆĘŁŃÓŚŹŻ]))|\bprzed \d+ stopni\b|\b(?:stycznia|lutego|marca|kwietnia|maja|czerwca|lipca|sierpnia|września|października|listopada|grudnia) \d{4} rok\b", re.IGNORECASE)
UNSAFE_SPOKEN_DECIMAL_RE = re.compile(rf"\bzero[,.]\d+\b|\bw \d+\s+(?:idę|idziesz|idziemy)\b|\b(?:dzień|miesiąc|minuta|rok|sekunda|tydzień) \d+[,.]\d+\b|\bw ciągu ostatnich (?:tylko )?\d+(?:[,.]\d+)?%|\bponad \d{{1,2}} (?:{MONTHS})\b", re.IGNORECASE)
UNSAFE_DECLENSION_RE = re.compile(r"\b[2-9]\d* (?:pierwszą|drugą|trzecią|czwartą|piątą|szóstą|siódmą|ósmą|dziewiątą)\b|\b[234] (?:drugie|trzecie|czwarte|piąte|szóste|siódme|ósme|dziewiąte|dziesiąte) (?:tysiące|miliony|miliardy)\b|\b\d+ (?:osobow|tonow|tysięczn|milionow|miliardow)\w+\b|\bz \d+% \w+(?:em|ą)\b|\bw \d+ Państwa\b|\b\w+ich \d+-letni\b", re.IGNORECASE)
UNSAFE_FRAGMENT_RE = re.compile(rf"\b\d+ ostatnimi\b|\bPo \d+ przestałem\b|\bprzy \d+ kilku\b|\bna podstawie(?:\s+\w+){{3,}}\s+\d+ lat\b|\bna podstawie\b[^.!?]{{0,80}},[^.!?]{{0,40}}\b\d+ lat\b|\bw ciągu \d+ (?-i:[A-ZĄĆĘŁŃÓŚŹŻ])|(?:^|[.!?]\s+)\d+ lat (?-i:[A-ZĄĆĘŁŃÓŚŹŻ]\w+ [A-ZĄĆĘŁŃÓŚŹŻ]\w+)|\b(?:na|w) tym \d{{1,2}} (?:{MONTHS})\b|\b(?:po|przed) \w+ach w \d{{1,2}} (?:{MONTHS})\b|\b(?:poniedziałek|wtorek|środę|czwartek|piątek|sobotę|niedzielę) \d{{1,2}}\b|\bod roku \d{{1,2}} (?:{MONTHS})\b|\bw \d+ dni \d+ dni\b|\bjakoś \d{{3,4}} roku\b|\bod koniec roku \d{{3,4}}\b|\bczyli lat [2-9]0[.] \w+(?:u|a|i|y)\b|\bna około \d+\b|(?<!\bw )\bwieku \d+ lat\b|\b(?:w )?wiek \d+ lat\b|\b\d+ lat lat\b|\b(?-i:[A-ZĄĆĘŁŃÓŚŹŻ][a-ząćęłńóśźż]+) to \d+ lat,?\s+któr\w*\b|\b(?:one|oni) były \d+ (?:tysiąc|tysiące|tysięcy|milion|miliony|milionów|miliard|miliardy|miliardów)\b", re.IGNORECASE)
UNSAFE_REPEATED_QUANTITY_RE = re.compile(r"\b(?P<value>\d+) (?P<noun>tysiące|miliony|miliardy) (?P=value) (?P=noun)\b|\b\d+ (?P<scale>tysiąc|tysiące|tysięcy|milion|miliony|milionów|miliard|miliardy|miliardów) (?P=scale)\b|\b\d+ (?P<repeated_context>\w+) \w+ (?P=repeated_context)\b|\b(?:około|blisko|poniżej|powyżej|od|do) \d+ \w+(?:,| i| oraz| lub| albo) \d+ \w+|\b(?:dla|od|do|około|poniżej|powyżej) \d+(?: (?:tysiąc|tysiące|tysięcy|milion|miliony|milionów))? (?P<elliptical_noun>\w+)[?] \d+(?: (?:tysiąc|tysiące|tysięcy|milion|miliony|milionów))? (?P=elliptical_noun)[?]|\b\d+ (?:tysiąc|tysiące|tysięcy|milion|miliony|milionów|miliard|miliardy|miliardów) \d{3} \d{3}\b|\b\d+ (?:miliony|miliardy) \d+ (?:tysięcy|milionów)\b|\bulicy\b[^.!?]{0,40}\d+[-–]\d+|\bMatka \d+[-–]\d+", re.IGNORECASE)
UNSAFE_FOREIGN_RE = re.compile(r"[řščěýžíáéůťďňА-Яа-яЁё]|\b(?:jsme|kterého|osobu|metrů|bribes)\b", re.IGNORECASE)
HOUR_NOUN_RE = re.compile(r"(?<!\bdo )(?<!\bod )\b(?P<value>\d+) godziny\b")
UNSAFE_NOUN_FORM_RE = re.compile(r"\b\d+ (?:pary|tysiąc|lata|kilka|tle|lekcji|stuk)\b|\b\d{3,} centymetrowy\b|\b(?:Do lat|na lata) \d+(?:, \d+|[-–]\d+)+|\bw lat \d+\b|\bjako \d+ lat\b|\bw \d{1,3}(?: \d{3})+(?=[,.;!?]|$)|\bz \d+ metr\b|\bprzy \d+ pracowników\b|\b[A-ZĄĆĘŁŃÓŚŹŻ]\w+ \d+ Pro\b|\beuro \d+\b|\bz \d+[-–]\d+|\b\d+[-–]\d+-letni\b|\bważy\w* \d+ tonów\b|\bprzed \d+ stopni\b|\b(?:stycznia|lutego|marca|kwietnia|maja|czerwca|lipca|sierpnia|września|października|listopada|grudnia) \d{4} rok\b|\bz \d{4} rok\b|\bw \d{4} lat\b", re.IGNORECASE)
UNSAFE_BROKEN_PHRASE_RE = re.compile(r"\bpo \d+[,;]|,\s*\d+ minut[.!?]?\s*$|\bo \d+ lat\b|\bprzez około godzin i \d+ minut\b|\bpo (?:blisko|niemal|około|ponad|prawie) \d+ lat\b|\bpo(?:,)? (?:do )?lat \d+\b|\bod \d+ i \d+ sezon\b|\bw wieku niepełno \d+\b|\blatek \d+ do \d+|\b(?:z|na) (?:(?:blisko|około|ponad|prawie) )?\d+ lat temu\b|\b(?:te|tych) \d+ (?:dni|godzin|lat|miesięcy) (?:takim|takich|tym|tych) \w+\b|\b\d+ lat (?:ja|dziecko)\b|\bte (?:załóż\w*|założ\w*|powiedz\w*),? te \d+\b|\b(?:tak )?wiele \d+\b|\bte na \d+ lat\b|\b\d+ pół\b", re.IGNORECASE)
TOURNAMENT_FRACTION_RE = re.compile(r"\bw 1[./-](?P<divisor>2|4|8|16|32)[.]?(?=\s+(?:finał\w*|[A-ZĄĆĘŁŃÓŚŹŻ]))")
def _has_bad_hour_agreement(text: str) -> bool:
    return any(int(match["value"]) % 10 not in {2, 3, 4} or int(match["value"]) % 100 in {12, 13, 14}
               for match in HOUR_NOUN_RE.finditer(text))
def normalize_polish_numbers(text: str) -> str:
    """Expand a segment only when every digit belongs to a recognized expression."""
    unsafe_bible = BIBLE_REFERENCE_RE.sub("", text)
    unsafe_hyphens = AGE_ADJECTIVE_RE.sub("", unsafe_bible)
    unsafe_numbers = GROUPED_NUMBER_RE.sub("", unsafe_bible)
    unsafe_decimals = DOTTED_GROUPED_NUMBER_RE.sub("", CONTEXT_COMMA_CLOCK_RE.sub("", HOUR_CLOCK_RE.sub("", O_CLOCK_RE.sub("", unsafe_bible))))
    unsafe_ranges = TOURNAMENT_FRACTION_RE.sub("", unsafe_bible)
    unsafe_labels = TOURNAMENT_FRACTION_RE.sub(
        "", CLOCK_RE.sub("", COORDINATED_CLOCK_RE.sub("", HOUR_CLOCK_RE.sub("", O_CLOCK_RE.sub("", unsafe_bible))))
    )
    descending_percent = next((match for match in PERCENT_RANGE_RE.finditer(text)
                               if int(match["start"]) > int(match["end"])), None)
    wide_range = next((match for match in GENERIC_RANGE_RE.finditer(unsafe_ranges)
                       if int(match["end"]) > max(10, int(match["start"]) * 10)), None)
    if (descending_percent is not None or wide_range is not None
            or UNSAFE_NUMERIC_RE.search(unsafe_numbers)
            or UNSAFE_CONTEXT_RE.search(unsafe_bible)
            or UNSAFE_DECIMAL_NOUN_RE.search(unsafe_decimals)
            or UNSAFE_LABELED_DECIMAL_RE.search(unsafe_labels)
            or re.search(r"\bna \d+[.]\d+\b", unsafe_ranges)
            or UNSAFE_GRAMMAR_RE.search(GOVERNED_PERCENT_RE.sub("", expand_contextual_percentages(unsafe_bible)))
            or UNSAFE_NOUN_RANGE_RE.search(unsafe_ranges)
            or UNSAFE_SPACED_ALTERNATIVE_RE.search(unsafe_bible)
            or UNSAFE_SPACED_IDENTIFIER_RE.search(unsafe_bible)
            or UNSAFE_ALTERNATIVE_NOUN_RE.search(unsafe_bible)
            or UNSAFE_NOMINATIVE_DATE_RE.search(unsafe_bible)
            or UNSAFE_DUPLICATE_NUMBER_RE.search(unsafe_bible)
            or UNSAFE_CONSECUTIVE_PERCENT_RE.search(unsafe_bible)
            or UNSAFE_INVERTED_CONTEXT_RE.search(unsafe_bible) or UNSAFE_MALFORMED_CONTEXT_RE.search(unsafe_bible)
            or UNSAFE_SOURCE_GRAMMAR_RE.search(unsafe_bible)
            or UNSAFE_WORD_ORDER_RE.search(YEAR_NOMINATIVE_RE.sub("", unsafe_bible))
            or UNSAFE_SPOKEN_DECIMAL_RE.search(unsafe_bible)
            or UNSAFE_DECLENSION_RE.search(unsafe_bible)
            or UNSAFE_FRAGMENT_RE.search(unsafe_bible)
            or UNSAFE_REPEATED_QUANTITY_RE.search(unsafe_bible)
            or UNSAFE_FOREIGN_RE.search(unsafe_bible)
            or has_invalid_date(unsafe_bible) or has_invalid_mixed_range(unsafe_bible) or has_unsafe_number_syntax(unsafe_bible) or has_ambiguous_negated_percent(unsafe_bible) or has_ambiguous_dotted_group(unsafe_bible, DOTTED_GROUPED_NUMBER_RE)
            or _has_bad_hour_agreement(unsafe_bible)
            or UNSAFE_NOUN_FORM_RE.search(unsafe_bible)
            or UNSAFE_BROKEN_PHRASE_RE.search(unsafe_bible)
            or UNSAFE_HYPHEN_WORD_RE.search(unsafe_hyphens)
            or has_incompatible_cardinal_noun(re.sub(r"\bdo (?:minus )?\d+ potęgi\b", "", DATE_RE.sub("", ARTICLE_ORDINAL_RE.sub("", unsafe_hyphens)), flags=re.IGNORECASE), ORDINAL_LEMMAS)):
        return text
    normalized = expand_number_roles(re.sub(r"\b(?P<value>(?:\d*[02-9][234]|[234])) (?=(?:drugie|trzecie|czwarte|piąte|szóste|siódme|ósme|dziewiąte|dziesiąte)\b)", lambda match: f"{feminine_cardinal(int(match['value']))} ", re.sub(r"\b1 (?=(?:pierwszą|drugą|trzecią|czwartą|piątą|szóstą|siódmą|ósmą|dziewiątą|dziesiątą)\b)", "jedną ", DATE_RANGE_RE.sub(_date_range_words, expand_age_pair_labels(SPRZED_PONAD_RE.sub(lambda match: f"{match['prefix']} {_genitive_cardinal(int(match['value']))}{' ' + match['unit'] if match['unit'] else ''}", expand_completion_minutes(GOVERNED_PERCENT_RE.sub(_governed_percent_words, expand_contextual_percentages(expand_coordinated_measurements(CLOCK_RE.sub(_clock_words, expand_locative_scale_contexts(expand_embedded_cardinal_scales(text)))))))))), flags=re.IGNORECASE), flags=re.IGNORECASE))
    normalized = DATE_PAIR_RE.sub(_date_pair_words, normalized)
    normalized = CONTEXTUAL_DATE_RE.sub(lambda match: f"{match['prefix']} {(_locative_ordinal if match['about'] else _genitive_ordinal if match['today'] and match['prefix'].endswith(',') else _ordinal)(int(match['day']))} {match['month']}", normalized)
    normalized = MASCULINE_SUBJECT_DATE_RE.sub(lambda match: f"{match['prefix']}{_ordinal(int(match['day']))} {match['month']}", normalized)
    normalized = DEMONSTRATIVE_DATE_RE.sub(lambda match: f"po {match['context']} {_locative_ordinal(int(match['day']))} {match['month']}", normalized)
    normalized = SUBJECT_DATE_RE.sub(lambda match: f"{match['boundary'] or match['arrival']}{_ordinal(int(match['day'] or match['arrival_day']))} {match['month'] or match['arrival_month']}", normalized)
    normalized = PASSIVE_DATE_RE.sub(lambda match: f"{match['prefix']} {_genitive_ordinal(int(match['day']))} {match['month']}", normalized)
    normalized = ACCUSATIVE_DATE_RE.sub(lambda match: f"{match['prefix']} {(_locative_ordinal if match['prefix'].lower() == 'przed' else _genitive_ordinal if match['prefix'].lower() in {'mam', 'mamy', 'na'} else _ordinal)(int(match['day']))} {match['month']}{f' {_genitive_ordinal(int(match["year"]))}{match["roku"] or ""}' if match['year'] else ''}", normalized)
    normalized = DATE_RE.sub(_date_words, normalized)
    normalized = YEAR_LIST_RE.sub(_year_list_words, normalized)
    normalized = YEAR_IN_PAIR_RE.sub(lambda match: f"{match['prefix']} {_locative_ordinal(int(match['first']))} {match['link']} {_locative_ordinal(int(match['second']))}", normalized)
    normalized = YEAR_PAIR_RE.sub(_year_pair_words, normalized)
    normalized = THIS_YEAR_RE.sub(lambda match: f"w tym roku {_locative_ordinal(int(match['year']))}", normalized)
    normalized = END_YEAR_RE.sub(lambda match: f"do końca {_genitive_ordinal(int(match['year']))}", normalized)
    normalized = LOCATIVE_MONTH_YEAR_RE.sub(lambda match: f"{match['prefix']} {match['month']} {_genitive_ordinal(int(match['year']))}", normalized)
    normalized = MONTH_YEAR_RE.sub(lambda match: f"{match['month']} {_genitive_ordinal(int(match['year']))}", normalized)
    normalized = YEAR_AFTER_PO_RE.sub(lambda match: f"{match['prefix']} {_locative_ordinal(int(match['year']))} roku", normalized)
    normalized = YEAR_AFTER_IN_RE.sub(year_after_in_words, normalized)
    normalized = YEAR_IN_RE.sub(lambda match: f"{match['prefix']} {match['modifier'] or ''}{_locative_ordinal(int(match['year']))} roku", normalized)
    normalized = YEAR_RE.sub(_year_words, normalized)
    normalized = YEAR_AFTER_RE.sub(lambda match: f"{match['governor'] or ''}{match['prefix']} {(_locative_ordinal if match['governor'] else _genitive_ordinal)(int(match['year']))}", normalized)
    normalized = YEAR_BEFORE_RE.sub(lambda match: f"{match['prefix']} {_locative_ordinal(int(match['year']))} rokiem", normalized)
    normalized = YEAR_TARGET_RE.sub(lambda match: f"{match['prefix']} {_ordinal(int(match['year']))}", normalized)
    normalized = YEAR_AFTER_ROK_RE.sub(lambda match: f"{match['prefix']} {(_cardinal if re.match(r'\s+(?:któryś|jakiś)\b', match.string[match.end():], re.IGNORECASE) else _ordinal)(int(match['year']))}", normalized)
    normalized = YEAR_NOMINATIVE_RE.sub(lambda match: f"{_ordinal(int(match['year']))} rok", normalized)
    normalized = SHORT_YEAR_RE.sub(lambda match: f"{match['prefix']} {_locative_ordinal(int(match['year']))} roku", normalized)
    normalized = SHORT_YEAR_NOMINATIVE_RE.sub(lambda match: f"{_ordinal(int(match['year']))} rok", normalized)
    normalized = SHORT_YEAR_AFTER_RE.sub(short_year_after_words, normalized)
    normalized = BCE_YEAR_RE.sub(lambda match: f"{match['prefix']} {_locative_ordinal(int(match['year']))} r.", normalized)
    normalized = AGE_AFTER_LAT_RE.sub(lambda match: f"{match['prefix']} lat {_cardinal(int(match['value']))}", normalized)
    normalized = LAT_DECADE_PAIR_RE.sub(_lat_decade_pair_words, normalized)
    normalized = LATA_DECADE_LIST_RE.sub(_lata_decade_list_words, normalized)
    normalized = DECADE_RE.sub(_decade_words, normalized)
    normalized = LAT_DECADE_RE.sub(_lat_decade_words, normalized)
    normalized = LATA_DECADE_RE.sub(_lata_decade_words, normalized)
    normalized = expand_contextual_percentages(normalized)
    normalized = PERCENT_RANGE_RE.sub(_range_percent_words, normalized)
    normalized = AGE_RANGE_RE.sub(_age_range_words, normalized)
    normalized = PO_ALTERNATIVE_RE.sub(_po_alternative_words, normalized)
    normalized = RANGE_RE.sub(_range_words, normalized)
    normalized = BIBLE_REFERENCE_RE.sub(lambda match: f"{match['label']} {_cardinal(int(match['chapter']))} {_cardinal(int(match['verse']))}", normalized)
    normalized = SPORTS_RECORD_RE.sub(lambda match: f"{match['label']} {_cardinal(int(match['wins']))} do {_genitive_cardinal(int(match['losses']))}", normalized)
    normalized = O_CLOCK_RE.sub(_o_clock_words, normalized)
    normalized = _expand_context_comma_clocks(normalized, CONTEXT_COMMA_CLOCK_RE)
    normalized = TIME_RANGE_RE.sub(_time_range_words, normalized)
    normalized = MINUTE_ALTERNATIVE_RE.sub(_minute_alternative_words, normalized)
    normalized = WORK_UNTIL_RE.sub(lambda match: f"Pracuję do {_feminine_ordinal(int(match['hour']))}", normalized)
    normalized = APPROXIMATE_RANO_RE.sub(lambda match: f"około {_feminine_ordinal(int(match['hour']))} rano", normalized)
    normalized = O_RANO_RE.sub(lambda match: f"o {_feminine_ordinal(int(match['hour']))} rano", normalized)
    normalized = HOUR_ACCUSATIVE_RE.sub(lambda match: f"{match['prefix'] or ''}{match['noun']} {_feminine_accusative_ordinal(int(match['hour']))}", normalized)
    normalized = HOUR_GENITIVE_RE.sub(lambda match: f"{match['noun']} {_feminine_ordinal(int(match['hour']))}", normalized)
    normalized = HOUR_BEFORE_RE.sub(lambda match: f"przed godziną {_feminine_accusative_ordinal(int(match['hour']))}", normalized)
    normalized = COORDINATED_CLOCK_RE.sub(_governed_clock_words, normalized)
    normalized = HOUR_CLOCK_RE.sub(_governed_clock_words, normalized)
    normalized = CLOCK_RE.sub(_clock_words, normalized)
    normalized = GOVERNED_PERCENT_RE.sub(_governed_percent_words, normalized)
    normalized = PERCENT_CONTEXT_RE.sub(lambda match: f"w granicach {_genitive_cardinal(int(match['value']))} procent", normalized)
    normalized = DEMONSTRATIVE_PERCENT_RE.sub(lambda match: f"{match['prefix']} tych {_genitive_cardinal(int(match['value']))} procentach", normalized)
    normalized = THOSE_PERCENT_RE.sub(lambda match: f"tych {_genitive_cardinal(int(match['value']))} procent", normalized)
    normalized = DEMONSTRATIVE_GOVERNED_RE.sub(lambda match: f"{match['prefix']} {match['modifier']} {_genitive_cardinal(int(match['value']))}", normalized)
    normalized = DEMONSTRATIVE_RE.sub(demonstrative_cardinal_words, normalized)
    normalized = FEMININE_DEMONSTRATIVE_RE.sub(lambda match: f"{match['prefix']} tej {_feminine_ordinal(int(match['value']))}", normalized)
    normalized = AGE_YEAR_RE.sub(lambda match: f"{match['prefix']} {_genitive_ordinal(int(match['value']))} roku życia", normalized)
    normalized = AGE_YEAR_AFTER_RE.sub(lambda match: f"{match['prefix']} {_locative_ordinal(int(match['value']))} roku życia", normalized)
    normalized = AGE_YEAR_ABOVE_RE.sub(lambda match: f"{match['prefix']} {_genitive_ordinal(int(match['value']))} roku życia", normalized)
    normalized = PRZEZ_OKOLO_RE.sub(lambda match: f"{match['prefix']} {match['modifier']} {_cardinal(int(match['value']))}", normalized)
    normalized = MODIFIED_GOVERNED_RE.sub(lambda match: f"{match['prefix']} {match['modifier'] or ''}{_genitive_cardinal(int(match['value']))}", normalized)
    normalized = expand_grouped_scales(normalized)
    normalized = DOTTED_GROUPED_NUMBER_RE.sub(dotted_group_words, normalized)
    normalized = GOVERNED_GROUPED_NUMBER_RE.sub(lambda match: f"{match['prefix']} {(_locative_cardinal if match['prefix'].lower().startswith('skończ') else _genitive_cardinal)(int(match['value'].replace(' ', '')))}", normalized)
    normalized = AGE_ADJECTIVE_RE.sub(_age_adjective_words, normalized)
    normalized = AGO_YEARS_RE.sub(lambda match: f"{match['prefix'] or ''}{(_genitive_cardinal if match['prefix'] else _cardinal)(int(match['value']))} lat temu", normalized)
    normalized = AFTER_DURATION_RE.sub(lambda match: f"{_cardinal(int(match['value']))} lat {match['link']}", normalized)
    normalized = HOUR_NOUN_RE.sub(lambda match: f"{feminine_cardinal(int(match['value']))} godziny", normalized)
    normalized = ARTICLE_ORDINAL_RE.sub(lambda match: f"{match['noun']} {(_cardinal if match['noun'].lower() == 'artykuł' and article_number_is_quantity(match.string, match.end()) else _locative_ordinal if match['noun'].lower() in {'artykule', 'ustępie'} else _genitive_ordinal if match['noun'].lower() in {'artykułu', 'ustępu'} else _ordinal)(int(match['value']))}", normalized)
    normalized = expand_morphological_numbers(CURRENCY_RE.sub(_currency_noun_phrase, normalized))
    normalized = GROUPED_NUMBER_RE.sub(lambda match: _cardinal(int(match.group().replace(" ", ""))), normalized)
    normalized = NEGATED_PERCENT_RE.sub(_negated_percent_words, normalized)
    normalized = PERCENT_RE.sub(lambda match: f"{_number_words(match['value'])} procent", normalized)
    normalized = expand_dimensions(normalized, DIMENSION_RE)
    normalized = LOCATIVE_POSITION_RE.sub(lambda match: f"{match['prefix']} {_locative_ordinal(int(match['value']))}" if match['prefix'] else f"{match['verb']} {_locative_ordinal(int(match['static_value']))} miejscu", normalized)
    normalized = NOMINATIVE_ORDINAL_RE.sub(lambda match: f"{_ordinal(int(match['value']))} {match['noun']}", normalized)
    normalized = KILOMETER_ORDINAL_RE.sub(lambda match: f"kilometra {_genitive_ordinal(int(match['value']))}", normalized)
    normalized = DAY_NUMBER_RE.sub(lambda match: f"{match['prefix']} dnia {_genitive_ordinal(int(match['value']))}", normalized)
    normalized = DAY_ORDINAL_RE.sub(lambda match: f"{match['prefix']} {_genitive_ordinal(int(match['value']))} dnia", normalized)
    normalized = NEGATED_QUANTITY_RE.sub(lambda match: f"nie przekracza {_genitive_cardinal(int(match['value']))}", normalized)
    normalized = FEMININE_GENITIVE_ORDINAL_RE.sub(lambda match: f"{_feminine_ordinal(int(match['value']))} {match['noun']}", normalized)
    normalized = EXPLICIT_ORDINAL_RE.sub(lambda match: f"{nominative_ordinal_for_noun(int(match['value']), match['noun'])} {match['noun']}", normalized)
    normalized = TOURNAMENT_FRACTION_RE.sub(lambda match: f"w jednej {_feminine_ordinal(int(match['divisor']))}", normalized)
    normalized = DECIMAL_RE.sub(_decimal_words, normalized)
    normalized = restore_numeric_sentence_capitals(text, normalized)
    return text if DIGIT_RE.search(normalized) else normalized
