import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowUpDown,
  AudioLines,
  BarChart3,
  Box,
  ChevronDown,
  ChevronsLeft,
  ChevronsRight,
  CircleCheckBig,
  CirclePlay,
  CircleX,
  Copy,
  Database,
  Download,
  ExternalLink,
  FileAudio,
  FlaskConical,
  Flag,
  FolderOpen,
  Gauge,
  GripVertical,
  Inbox,
  ListChecks,
  Loader,
  Maximize,
  Merge,
  Mic,
  Pause,
  Play,
  Plus,
  RefreshCw,
  Repeat,
  Rewind,
  Scissors,
  Search,
  Server,
  Settings,
  SkipBack,
  SkipForward,
  SlidersHorizontal,
  Sparkles,
  SquarePen,
  Trash2,
  Upload,
  Volume2,
  Wand2,
  Workflow,
  X,
  ZoomIn,
  ZoomOut,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Design icon name -> Lucide component. Names mirror the source mockup's ICONS map. */
const ICONS = {
  sliders: SlidersHorizontal,
  database: Database,
  mic: Mic,
  "audio-lines": AudioLines,
  "bar-chart": BarChart3,
  activity: Activity,
  box: Box,
  flask: FlaskConical,
  "list-checks": ListChecks,
  settings: Settings,
  "chevrons-left": ChevronsLeft,
  "chevrons-right": ChevronsRight,
  "chevron-down": ChevronDown,
  check: CircleCheckBig,
  "check-plain": CircleCheckBig,
  x: X,
  alert: AlertTriangle,
  loader: Loader,
  "check-circle": CircleCheckBig,
  plus: Plus,
  upload: Upload,
  trash: Trash2,
  bolt: Zap,
  search: Search,
  play: Play,
  pause: Pause,
  "skip-back": SkipBack,
  "skip-fwd": SkipForward,
  "arrow-left": ArrowLeft,
  scissors: Scissors,
  merge: Merge,
  wand: Wand2,
  sort: ArrowUpDown,
  "file-audio": FileAudio,
  inbox: Inbox,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
  repeat: Repeat,
  volume: Volume2,
  rewind: Rewind,
  flag: Flag,
  gauge: Gauge,
  "x-circle": CircleX,
  download: Download,
  "folder-open": FolderOpen,
  edit: SquarePen,
  copy: Copy,
  external: ExternalLink,
  refresh: RefreshCw,
  sparkles: Sparkles,
  "play-circle": CirclePlay,
  server: Server,
  workflow: Workflow,
  grip: GripVertical,
  maximize: Maximize,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  size = 18,
  className,
  strokeWidth = 2,
}: {
  name: IconName;
  size?: number;
  className?: string;
  strokeWidth?: number;
}) {
  const Cmp = ICONS[name];
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} />;
}
